language: node_js
node_js: 
  - '8'
cache: 
  - yarn
before-script: 
  - yarn
script: 
  - yarn prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist
  keep_history: true
  on:
    branch: github-pages