language: node_js
node_js: 
  - '8'
cache: 
  - yarn
branches:
  only:
  - master
before-script: 
  - yarn
script: 
  - yarn prod
deploy:
  provider: surge
  domain: workshops-fe-gm.surge.sh
  project: ./dist
  github_token: $GITHUB_TOKEN
  skip_cleanup: true