language: node_js
node_js: 
  - '8'
cache: 
  - yarn
branches:
  only:
  - master
before-script: 
  - yarn
script: 
  - yarn prod
deploy:
  provider: heroku
  local_dir: ./dist
  api_key: 
    secure: $HEROKU_FE_COURSES_KEY
  app: workshops-fe-gm