language: node_js
node_js: 
  - '8'
cache: 
  - yarn
branches:
  only:
  - master
  - heroku-app
before-script: 
  - yarn
script: 
  - yarn prod
before_deploy:
  - cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: 
    secure: $HEROKU_FE_COURSES_KEY
  app: workshops-fe-gm
  on:
    branch: heroku-app