language: node_js
node_js: 
  - '8'
cache: 
  - yarn
branches:
  only:
  - master
before-script: 
  - yarn
script: 
  - yarn prod
deploy:
  provider: pages
  local_dir: ./dist
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true